#ifndef TIMERHAL_CFG_H_
#define TIMERHAL_CFG_H_

#define TIMER_IS_USED
#define TIMER_USE_CALLBACK
#define PRESCALER_BITMASK 3
#define TIMER_RESOLUTION_MS
#define TIMER_COUNTER_START_VALUE 156
#define TIMER_LIMIT 1
#endif